const stages = [
  ['만두', '🥟', 5.2, 110, 'steady'], ['만두', '🥟', 4.8, 90, 'steady'], ['만두', '🥟', 4.4, 75, 'steady'], ['만두', '🥟', 4.0, 65, 'flicker'], ['만두', '🥟', 3.65, 55, 'flicker'], ['만두', '🥟', 3.3, 48, 'warp'], ['만두', '🥟', 2.95, 42, 'warp'], ['만두', '🥟', 2.55, 36, 'pulse'], ['만두', '🥟', 2.15, 30, 'pulse'], ['만두', '🥟', 1.75, 24, 'chaos'],
].map(([dish, food, seconds, tolerance, effect], index) => ({ dish, food, seconds, tolerance, effect, final:index === 9 }));
const $ = id => document.getElementById(id);
const ui = {stage:$('stage'),dish:$('dish'),best:$('best'),precision:$('precision'),timer:$('timer'),timerUnit:$('timer-unit'),timerCaption:$('timer-caption'),food:$('food'),microwave:$('microwave'),overlay:$('phase-overlay'),phaseTitle:$('phase-title'),phaseCopy:$('phase-copy'),goal:$('goal'),tolerance:$('tolerance'),button:$('start-button'),message:$('message'),modal:$('nickname-modal'),form:$('nickname-form'),input:$('nickname-input'),ranking:$('ranking-list')};
let stage=0, active=false, animation, startAt, nickname=localStorage.getItem('microwaveZeroNickname')||'', best=Number(localStorage.getItem('microwaveZeroBest')||1), runPeak=1, audioContext, humOscillator, humGain;
ui.best.textContent=String(best).padStart(2,'0');
function say(text,kind=''){ui.message.textContent=text;ui.message.className=kind}function context(){audioContext??=new(window.AudioContext||window.webkitAudioContext)();return audioContext}function tone(freq=240,length=.04,volume=.028){try{const c=context(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;g.gain.setValueAtTime(volume,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+length);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+length)}catch{}}function startHum(){try{const c=context();if(c.state==='suspended')c.resume();stopHum();humOscillator=c.createOscillator();humGain=c.createGain();humOscillator.type='sawtooth';humOscillator.frequency.value=78;humGain.gain.setValueAtTime(.018,c.currentTime);humOscillator.connect(humGain).connect(c.destination);humOscillator.start()}catch{}}function stopHum(){if(!humOscillator)return;try{humGain.gain.exponentialRampToValueAtTime(.001,context().currentTime+.06);humOscillator.stop(context().currentTime+.07)}catch{}humOscillator=null;humGain=null}function finishDing(){try{const c=context(),start=c.currentTime;[1046,1568].forEach((freq,index)=>{const o=c.createOscillator(),g=c.createGain();o.type='triangle';o.frequency.value=freq;g.gain.setValueAtTime(.001,start+index*.16);g.gain.exponentialRampToValueAtTime(.16,start+index*.16+.012);g.gain.exponentialRampToValueAtTime(.001,start+index*.16+.8);o.connect(g).connect(c.destination);o.start(start+index*.16);o.stop(start+index*.16+.85)})}catch{}}function failureSound(){try{const c=context(),start=c.currentTime,o=c.createOscillator(),g=c.createGain(),lfo=c.createOscillator(),lfoGain=c.createGain();o.type='sawtooth';o.frequency.setValueAtTime(240,start);o.frequency.exponentialRampToValueAtTime(48,start+.9);lfo.frequency.value=13;lfoGain.gain.value=28;lfo.connect(lfoGain).connect(o.frequency);g.gain.setValueAtTime(.001,start);g.gain.exponentialRampToValueAtTime(.11,start+.02);g.gain.setValueAtTime(.08,start+.28);g.gain.exponentialRampToValueAtTime(.001,start+1.05);o.connect(g).connect(c.destination);o.start(start);lfo.start(start);o.stop(start+1.08);lfo.stop(start+1.08)}catch{}}
function show(title,copy){ui.phaseTitle.textContent=title;ui.phaseCopy.textContent=copy;ui.overlay.classList.add('visible')}function hide(){ui.overlay.classList.remove('visible')}
function configure(){const current=stages[stage];ui.stage.textContent=String(stage+1).padStart(2,'0');ui.dish.textContent=current.dish;ui.goal.textContent='0.0초에서 정지';ui.tolerance.textContent=`오차 ±${current.tolerance}ms`;ui.timer.textContent='--.-';ui.timerCaption.textContent='ZERO TARGET';ui.timerUnit.classList.remove('target-now','last-second');ui.precision.textContent='--';ui.microwave.classList.remove('done');ui.microwave.dataset.effect=current.effect}
function scores(){try{return JSON.parse(localStorage.getItem('microwaveZeroRanks')||'[]')}catch{return[]}}function esc(value){const n=document.createElement('span');n.textContent=value;return n.innerHTML}function render(){const values=scores();ui.ranking.innerHTML=values.length?values.map((v,i)=>`<li><span class="rank-number">${i+1}</span><strong>${esc(v.name)}</strong><span>${v.stage}단계</span></li>`).join(''):'<li class="empty-rank">아직 전자레인지 신이 없습니다.</li>'}function save(peak){if(!nickname)return;const all=scores(),old=all.find(v=>v.name===nickname);if(old)old.stage=Math.max(old.stage,peak);else all.push({name:nickname,stage:peak});all.sort((a,b)=>b.stage-a.stage||a.name.localeCompare(b.name));localStorage.setItem('microwaveZeroRanks',JSON.stringify(all.slice(0,10)));render()}
function countdown(){configure();ui.button.disabled=true;ui.button.textContent='가동 준비 중...';show(`STAGE ${String(stage+1).padStart(2,'0')} · READY`,stages[stage].dish);setTimeout(()=>{show('3','전자레인지 문을 닫으세요');tone(330)},700);setTimeout(()=>{show('2','0.0초에 멈춰야 합니다');tone(410)},1400);setTimeout(()=>{show('1','과열은 용서되지 않습니다');tone(500)},2100);setTimeout(()=>{hide();active=true;startAt=performance.now();ui.microwave.classList.add('running','shaking');startHum();tick(startAt);tone(650,.07)},2800)}
function start(){if(!active&&!ui.button.disabled&&nickname){runPeak=1;countdown()}}function tick(now){if(!active)return;const current=stages[stage],elapsed=(now-startAt)/1000,raw=current.seconds-elapsed,inside=Math.abs(raw)<=current.tolerance/1000,shown=inside?0:raw;ui.timer.textContent=`${shown<0?'-':''}${Math.abs(shown).toFixed(1)}`;ui.timerUnit.classList.toggle('last-second',raw<=1&&raw>current.tolerance/1000);ui.timerUnit.classList.toggle('target-now',inside);ui.timerCaption.textContent=inside?'NOW! STOP!':raw<=1&&raw>0?'GET READY':'ZERO TARGET';if(raw<-.8)return fail('너무 늦었습니다. 만두가 새로운 생명체가 되었습니다.');animation=requestAnimationFrame(tick)}
function stop(){if(!active)return;const current=stages[stage],raw=current.seconds-(performance.now()-startAt)/1000,miss=Math.round(Math.abs(raw)*1000);cancelAnimationFrame(animation);active=false;stopHum();ui.microwave.classList.remove('running','shaking');ui.timerUnit.classList.remove('target-now','last-second');ui.precision.textContent=miss;if(miss>current.tolerance)return fail(`${miss}ms 차이입니다. 0초의 벽은 높았습니다.`);clear(miss)}
function clear(miss){const current=stages[stage];ui.microwave.classList.add('overcooked','done');say(`${String(stage+1).padStart(2,'0')}단계 성공! 오차 ${miss}ms. ${current.dish}이(가) 완벽하게 데워졌습니다.`, 'success');show('PERFECT!',`${current.dish} 조리 완료 · 오차 ${miss}ms`);finishDing();if(current.final)return setTimeout(win,1400);stage++;runPeak=Math.max(runPeak,stage+1);best=Math.max(best,runPeak);localStorage.setItem('microwaveZeroBest',best);ui.best.textContent=String(best).padStart(2,'0');setTimeout(()=>{ui.microwave.classList.remove('overcooked');countdown()},1900)}
function finish(){active=false;cancelAnimationFrame(animation);stopHum();ui.microwave.classList.remove('running','shaking','overcooked');ui.button.disabled=false;ui.button.textContent='1단계부터 다시 돌리기'}function fail(reason){finish();save(runPeak);stage=0;configure();ui.timer.textContent='ERR';say(`${reason} 최고 ${runPeak}단계 기록 후 1단계로 초기화됩니다.`,'danger');show('BEEP BEEP', '전자레인지가 깊은 한숨을 쉽니다');failureSound()}function win(){finish();save(10);ui.timer.textContent='0.0';say('완벽합니다. 마지막 만두가 가장 이상적인 온도에 도달했습니다. 당신은 0초 조절의 신입니다.','success');show('ZERO GOD!', '10단계 완주 · 만두의 신화 탄생');tone(1100,.35)}
ui.button.addEventListener('click',start);window.addEventListener('keydown',e=>{if(e.code!=='Space')return;e.preventDefault();if(!e.repeat)active?stop():start()});ui.form.addEventListener('submit',e=>{e.preventDefault();const value=ui.input.value.trim().slice(0,15);if(!value)return;nickname=value;localStorage.setItem('microwaveZeroNickname',nickname);ui.modal.classList.add('hidden');say(`${nickname} 님, 0초의 세계에 오신 걸 환영합니다.`)});if(nickname)ui.modal.classList.add('hidden');else setTimeout(()=>ui.input.focus(),100);configure();render();
