const rows=['QWERTYUIOP','ASDFGHJKL','ZXCVBNM'];
const keys=[...rows.join('')]; const total=15;
const keyboard=document.querySelector('#keyboard'),targetEl=document.querySelector('#target'),meter=document.querySelector('#meter'),savedEl=document.querySelector('#saved'),mistakesEl=document.querySelector('#mistakes'),leftEl=document.querySelector('#left'),textEl=document.querySelector('#text'),note=document.querySelector('#note'),status=document.querySelector('#status'),catWord=document.querySelector('#cat-word'),catCopy=document.querySelector('#cat-copy');
let target='',saved=0,mistakes=0,active=false,timer,startedAt,round=0,cycle=0,roundDuration=1700;
const phrases=['오','늘','도','문','서','를','무','사','히','작','성','한','다','!',''];
function tone(freq,d=.08){try{const C=window.AudioContext||window.webkitAudioContext,c=tone.c||(tone.c=new C());if(c.state==='suspended')c.resume();const o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.06,c.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+d+.02)}catch{}}
function render(){savedEl.textContent=String(saved).padStart(2,'0');mistakesEl.textContent=String(mistakes).padStart(2,'0');leftEl.textContent=`${String(Math.min(round+1,total)).padStart(2,'0')} / ${total}`;document.querySelectorAll('.key').forEach(k=>k.classList.toggle('target',k.dataset.key===target));}
function updateMeter(id){if(!active||id!==cycle)return;const elapsed=performance.now()-startedAt;meter.style.width=`${Math.min(100,elapsed/roundDuration*100)}%`;if(elapsed>=roundDuration)return catWins();requestAnimationFrame(()=>updateMeter(id))}
function next(){if(round>=total)return finish();roundDuration=Math.max(1080,1700-round*45);target=keys[Math.floor(Math.random()*keys.length)];startedAt=performance.now();cycle++;catWord.textContent='앞발 접근 중';catCopy.textContent=`${target} 키를 노립니다 · 제한 ${(roundDuration/1000).toFixed(1)}초`;status.textContent='방어 중';note.textContent='빛나는 키를 먼저 눌러주세요.';render();requestAnimationFrame(()=>updateMeter(cycle))}
function defend(key){if(!active||key!==target)return;if(performance.now()-startedAt>roundDuration)return catWins();document.querySelector(`.key[data-key="${key}"]`).classList.add('hit');setTimeout(()=>document.querySelector(`.key[data-key="${key}"]`)?.classList.remove('hit'),180);saved++;round++;textEl.innerHTML+=`${phrases[round-1]||''}<span class="cursor">|</span>`;next()}
function catWins(){if(!active)return;mistakes++;round++;textEl.innerHTML=textEl.innerHTML.replace('<span class="cursor">|</span>','')+`<b class="cat-typo">ㅁㅇㄴ</b><span class="cursor">|</span>`;catWord.textContent='키보드 점령!';catCopy.textContent=`${target} 키를 먼저 밟았습니다.`;note.textContent='고양이 오타가 문서에 남았습니다…';tone(120,.18);next()}
function finish(){active=false;meter.style.width='0';status.textContent='작성 완료';const modal=document.querySelector('#result');document.querySelector('#result-title').textContent=mistakes<=3?'문서 사수 성공!':'고양이와 공동 작성';document.querySelector('#result-copy').textContent=`${total}번 중 ${saved}번을 막았고, 고양이 오타는 ${mistakes}개입니다.`;modal.hidden=false}
function start(){clearTimeout(timer);saved=0;mistakes=0;round=0;active=true;target='';textEl.innerHTML='<span class="cursor">|</span>';document.querySelector('#result').hidden=true;document.querySelector('#start').textContent='다시 작성하기';next()}
rows.forEach(row=>{const div=document.createElement('div');div.className='key-row';[...row].forEach(char=>{const button=document.createElement('button');button.className='key';button.type='button';button.dataset.key=char;button.textContent=char;button.addEventListener('click',()=>defend(char));div.append(button)});keyboard.append(div)});
document.querySelector('#start').addEventListener('click',start);document.querySelector('#again').addEventListener('click',start);window.addEventListener('keydown',e=>defend(e.key.toUpperCase()));render();
